import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  rmdirSync,
  statSync,
  utimesSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

/**
 * Materialize the assets a static web assets manifest declares into a single
 * directory.
 *
 * MSBuild scatters build output across `obj/fx`, `obj/webcil` and friends, but
 * Vite's alias and dev server want one directory that looks like a wwwroot.
 * Copying is a one-time cost per changed file: unchanged files are skipped by
 * comparing size and mtime, which is why copies stamp the source mtime onto the
 * target.
 */

/** Marks a directory as owned by this plugin, so pruning cannot delete elsewhere. */
export const stagingMarkerName = ".vite-plugin-dotnet-wasm";

export interface MaterializeOptions {
  /**
   * Whether to delete files in the target that the manifest no longer declares.
   * Fingerprinted names change on every build, so without this the staging
   * directory accumulates every asset the project has ever produced.
   * @default true
   */
  prune?: boolean;
}

export interface MaterializeResult {
  written: number;
  unchanged: number;
  removed: number;
}

/**
 * Resolve a served path against the staging directory, refusing anything that
 * would escape it. The manifest is SDK-generated and thus trusted, but a
 * traversal here would delete or overwrite files outside the plugin's control.
 */
export function resolveStagingPath(targetDir: string, route: string): string {
  const segments = route.split("/").filter((segment) => segment !== "");

  if (
    segments.length === 0 ||
    segments.some((segment) => segment === "." || segment === "..")
  ) {
    throw new Error(`Refusing to materialize the served path "${route}".`);
  }

  return join(targetDir, ...segments);
}

const isUpToDate = (source: string, target: string): boolean => {
  if (!existsSync(target)) {
    return false;
  }

  const sourceStat = statSync(source);
  const targetStat = statSync(target);

  // Compare the Date rather than mtimeMs: utimesSync writes millisecond
  // precision, so a sub-millisecond source timestamp never round-trips exactly.
  return (
    sourceStat.size === targetStat.size &&
    sourceStat.mtime.getTime() === targetStat.mtime.getTime()
  );
};

function listFiles(directory: string): string[] {
  if (!existsSync(directory)) {
    return [];
  }

  return readdirSync(directory, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => join(entry.parentPath, entry.name));
}

/** Remove directories that pruning emptied, deepest first. */
function removeEmptyDirectories(directory: string): void {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue;
    }

    const child = join(directory, entry.name);
    removeEmptyDirectories(child);
    if (readdirSync(child).length === 0) {
      rmdirSync(child);
    }
  }
}

function assertPrunable(targetDir: string): void {
  if (!existsSync(targetDir)) {
    return;
  }
  if (existsSync(join(targetDir, stagingMarkerName))) {
    return;
  }
  if (readdirSync(targetDir).length === 0) {
    return;
  }

  throw new Error(
    `Refusing to prune "${targetDir}": it holds files this plugin did not put there. ` +
      `Point the plugin at a directory it owns, or delete that one.`,
  );
}

/**
 * Copy every declared asset into `targetDir`, skipping files that are already
 * current and (by default) deleting files the manifest no longer declares.
 */
export function materializeAssets(
  files: ReadonlyMap<string, string>,
  targetDir: string,
  options: MaterializeOptions = {},
): MaterializeResult {
  const { prune = true } = options;
  const resolvedTarget = resolve(targetDir);

  if (prune) {
    assertPrunable(resolvedTarget);
  }

  mkdirSync(resolvedTarget, { recursive: true });
  writeFileSync(
    join(resolvedTarget, stagingMarkerName),
    "Generated by vite-plugin-dotnet-wasm. Safe to delete; it will be rebuilt.\n",
  );

  const expected = new Set<string>([join(resolvedTarget, stagingMarkerName)]);
  let written = 0;
  let unchanged = 0;

  for (const [route, source] of files) {
    const target = resolveStagingPath(resolvedTarget, route);
    expected.add(target);

    if (isUpToDate(source, target)) {
      unchanged += 1;
      continue;
    }

    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(source, target);
    // copyFileSync does not carry the mtime over, and the next run's staleness
    // check depends on it.
    const sourceStat = statSync(source);
    utimesSync(target, sourceStat.atime, sourceStat.mtime);
    written += 1;
  }

  let removed = 0;
  if (prune) {
    for (const existing of listFiles(resolvedTarget)) {
      if (expected.has(existing)) {
        continue;
      }
      rmSync(existing);
      removed += 1;
    }
    removeEmptyDirectories(resolvedTarget);
  }

  return { written, unchanged, removed };
}

/**
 * Served paths, relative to the staging directory, for the files it currently
 * holds. Useful for asserting what a build produced.
 */
export function listStagedRoutes(targetDir: string): string[] {
  return listFiles(resolve(targetDir))
    .map((file) => relative(resolve(targetDir), file).split(sep).join("/"))
    .filter((route) => route !== stagingMarkerName)
    .sort();
}
