name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: "10.x"

      - name: Install .NET WASM workloads
        run: dotnet workload install wasm-tools wasm-experimental

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          cache: "pnpm"

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10
          cache: true

      - run: pnpm install && pnpm run build

      - name: Install docs dependencies
        run: pnpm install
        working-directory: docs

      - name: Build docs
        run: pnpm run build
        working-directory: docs
        env:
          VITE_BASE: /vite-plugin-dotnet-wasm/

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: docs/dist
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
